# Generated by Django 4.1.1 on 2022-11-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_company_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
