# Generated by Django 4.1.1 on 2022-11-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.TextField(blank=True),
        ),
    ]
